language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
    coverage run --source=polling setup.py test
after_success:
  coveralls
